name: Build
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Prerequesties
      run: |
        sudo apt-get install cmake cppcheck doxygen python3-pip python3-setuptools
        sudo pip3 install cpplint conan
        conan remote add pureoop-2out https://conan.cloudsmith.io/pureoop/2out
        conan remote add pureoop-goost https://conan.cloudsmith.io/pureoop/goost
    - name: Build
      run: |
        conan install . -s compiler.libcxx='libstdc++11' --build goost --build 2out
        cmake .
        make style
        make VERBOSE=1
